language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- yarn
- cd functions && yarn && cd ..
script: echo "Deploying!"
before_deploy: npm run build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: dfua17
  token:
      secure: DZVojUiBcDMmXPxvO/mvD6VZnAPl5Hc85YeZJOwoWICiKWO5DyvYfGMVGubXyX0nlA/IpzhX+zqDupHCnmbKZE/9L9I4Pu5IwWVCedMODsLp87f8omiSvWzmF1yIwFJYMbjlyZbLJWGIafSbJdB9Wnb7Z91E2K7vnGXVnOnOmLRqQzofBGSQhz2eZbnj5xtIYm21XKiJTzpFjCzfigYUvFmhyjBfViVeeW4rllZQ5Pw9BT0wjKOhSX/8IecNy7hJpTVNMpF+5SfygDuNiE/7KrZTf+6bjeR0gP5lmVape5x/NwDmyJBxTqpAXB/SKi7azhz8Luu27RLf6SDEe8v716bw6oRylgk489u4VgTI+meIgJakX3xmh87aRGDmhfIZ4qc4gJOvGCDGwtCl62+v/PDJCH83Bz4fTaNNC+JJZm9SukPtQ4vx+hoQV0aABedBUqWvmAs6Dm34Vn+V42lmEP/q/xDFLQmfOEqon7dJbWOszy7X5EQicvooWryC5F1KMHQ+QP6tvWed589uVo2hJ3RpndZq4MH5d47RLPbL53IuMeDu0oXN8+w9tp3vtG1VFf0nZJDG2EmoG7ShGsjGtmzmtJYojhYxxCIsBFOugtcbuWQiriM4dDiGmRKO+wUqVoDQXsbb7HbMwEn2mO74Imuq8YobI4hd4Nxl78ourLE=
#- provider: firebase
#  skip_cleanup: true
#  on:
#    branch: master
#  project: dfua-test
#  token:
#    secure: JsBbMAAmT/1XkpWoEavvqHwNiy2AZrH2mUlpBDrZfuffmw74WHH4pGGLYIMBxdHnywitnk0BLz7Cvri7DiIn0AFly8h7qyNoSYv4h0YJKbeuWGQUlpffHEWKNEdhO9cl5xnkQewiBamHTieXrp/Gbqs2au/vPuGzvETRMvX50X8u+69idcdiQ/GCRTkd0RR7IU5hCZ9WhTFYvhrrnweL2xZnIYL73tNXa4eNqvGcyrEV3qvH+yMzFnPwo6rfK9c9YnrqwSeWdnjcAHjeSmiypc3GeD8OfiW1x3DWZP0hQ6JKIDnpXIodZd9EKh5ArrbRJwOguBIVT7TX05lf544JMcREOuee/MiMqsR1p1xdCd70pttQImb3yPIsv6F+iJK1QlIsN0MzplDwHpbKYRou4/vweTiefIbgrlVgCeIBVrRyA3pHmZlBibKCYYvFQwBzwHQjXs6WDgZkpt1Ddw1akfVdETNObaoNhth8rNA9MRDCUoS5aYqEorL9IN8eTd0sZMaNYFEsADSpXzx9sY66YqrY95nCoctMEF+mW83duiojcAjQshFEvS6HTqr7ZmCCHMZYNNSvDUZKys0ZFrUBGkvIvaZiakTXvLvO6/QgfqMRzt/NN0gLLqJWz9xMGlSfZtIF4mPYOcn3bClsIoECShGCHbDrE3Zqpy2x/wzkbBQ=
