language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install -g bower polymer-cli
- bower install
script: echo "Deploying!"
before_deploy: polymer build
deploy:
- provider: firebase
  skip_cleanup: true
  branch: master
  project: dfua16
  token:
    secure: pXjCmSFt/4ZFPrnYdfPYnGI2gkm20+XAvjdyHmpqnpRe0r50BeGrbLRarjPOgUy6T34N0MESZD8tdWcKke1yziVwPRzM0cKlKGHESSjKaFYSNIJDq2UmVI9f+ZiNX2iWewbxLqyM5XkIliQvpIPonrlFs24LNVeNFPFkRfP39sTHjqfj4QlEbscZ3RISTi/V5vq832PzHNpt8rV14XBzpVfzqM7PYBl9ES+hfIZKon6cNYrQEXHrScomG6urX8RBRw50EqOP+XhDKy+kHBVf36O2jJd1PiA/3v20ulPzPsIlRCP+KJbsnV/ZtgafEUtwaYc1DHbGq9F8Mcnh/TdO1PuJLrHjzuV4dIUvpAKKimUsliY8F4JjzTqE1miwEUjLbNiRK1jRn+e/GH9zzSTN7qctRfLKlwfqnUdicZ85u7NqxvASFZLJrY6mffPlJdJIgLXz91hCW3xdivHlOssROC0dcaHyP1eXm2ZP49B3issRwa2phBkZSUzp+8P9fNFw/nXkW+gasHzrGnzEbdZYKK2VvfklfUXuO4hWNOhEATGhfznY8xLCbZ0qtzwec6Mpw6aTw625+vbb4bgX8/IVNeaAk0ukAFnszwb0ZCaeRzD8b1/1Pof2V5e1MrNfh3ZYelwGGVqrtaNLa9w0CJ3adR/VpNma7uCDKxiWQfQHo1o=
