language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
script: echo "Deploying!"
before_deploy: npm run build
deploy:
#- provider: firebase
#  skip_cleanup: true
#  on:
#    branch: master
#  project: hoverboard-firebase
#  token:
#    secure: SFEDWy0rKbYf5lgSGNlgpF5pnTwczRqaZhqSLdBoFZTieiSXjVRRMou84JEyvVZjbcro1Pxmd9IiKOqpFeu2XNoklT2eXOb1pCBPMiquXbFW1ERVdL70ZVRK+Esr1SkK1yrKjy8N32zLMSkfpqTTcJJQbydt53plQLqx9A98pR8L+2I/Xew/bcjPtMbqVlh9bTYKBGq0LYXJCNMttRvh783wre5olGnKv9r416ghpX/NqEnzGhoiBVg3yLpZJVXLMxhsxWtyusHxz0LSunMbKLtaJbgyqtm1vkJhhl19K7/TQJCe3ELC35ujBSKJ1lVkDIYeldc0/Z8Z8LNq986CpntZMGcLQJyp97nUSJ37IOh4Bzn02UPeDqZfMh60P5Gyug4kGNJYTwL/z4SV6GvdoxOeXa5Gy4PFMyZGYB3DFM8yptEVtbaHIfgHxeCnY5+wdM95aVuMICiT71C8AXUqozjwpIzz68o1f7QsXMgWv55xxkvuLRbPahcli0Qh8IcnU42LfljZLvjAHQE+DpNjk7lvgXxEPD3icIqdmtKnX4R9trUJwLZaSUWEjNyiglg+/Ft2D40pBrlKce4qJlOvrZNKr+lK7t/XXgPjFoX46+cWyDHBo4WUMWtalhEnqR0AvxaF3LRmRZ20n6Xk7OHJwKWdIntI5cmZvf2KXIgxcPc=
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: dfua-test
  token:
    secure: JsBbMAAmT/1XkpWoEavvqHwNiy2AZrH2mUlpBDrZfuffmw74WHH4pGGLYIMBxdHnywitnk0BLz7Cvri7DiIn0AFly8h7qyNoSYv4h0YJKbeuWGQUlpffHEWKNEdhO9cl5xnkQewiBamHTieXrp/Gbqs2au/vPuGzvETRMvX50X8u+69idcdiQ/GCRTkd0RR7IU5hCZ9WhTFYvhrrnweL2xZnIYL73tNXa4eNqvGcyrEV3qvH+yMzFnPwo6rfK9c9YnrqwSeWdnjcAHjeSmiypc3GeD8OfiW1x3DWZP0hQ6JKIDnpXIodZd9EKh5ArrbRJwOguBIVT7TX05lf544JMcREOuee/MiMqsR1p1xdCd70pttQImb3yPIsv6F+iJK1QlIsN0MzplDwHpbKYRou4/vweTiefIbgrlVgCeIBVrRyA3pHmZlBibKCYYvFQwBzwHQjXs6WDgZkpt1Ddw1akfVdETNObaoNhth8rNA9MRDCUoS5aYqEorL9IN8eTd0sZMaNYFEsADSpXzx9sY66YqrY95nCoctMEF+mW83duiojcAjQshFEvS6HTqr7ZmCCHMZYNNSvDUZKys0ZFrUBGkvIvaZiakTXvLvO6/QgfqMRzt/NN0gLLqJWz9xMGlSfZtIF4mPYOcn3bClsIoECShGCHbDrE3Zqpy2x/wzkbBQ=
